import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "components/Navbar";
import MainContent from "components/MainContent/index";
import Footer from "components/Footer";

export interface HomeProps {
  text: string;
  author: string;
  tag: string;
}

export default function Home({ data }: { data: HomeProps[] }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dukkan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <MainContent data={data} />
      <Footer />
    </div>
  );
}

export async function getStaticProps(context: any) {
  let data: any[] = [];
  try {
    let res: any = await fetch(
      "https://goquotes-api.herokuapp.com/api/v1/random?count=90"
    );
    let json: any = await res.json();
    data = await json.quotes;
    return {
      props: {
        data,
      },
    };
  } catch (e) {
    console.log(e);
    return {
      props: {
        data,
      },
    };
  }
}
